language: isabelle
before_install:
  - wget http://isabelle.in.tum.de/dist/Isabelle2013-2_linux.tar.gz
  - sudo tar xf Isabelle2013-2_linux.tar.gz -C /opt/
  - sudo /opt/Isabelle2013-2/bin/isabelle install /usr/local/bin
  # Build basic theories
  - sudo isabelle build -v Pure
  - sudo isabelle build -v HOL
script:
  - isabelle build -v -D .
