before_install:
  - bash ./before_install.bash
script:
  - make "${EXERCISES}"
env:
  - EXERCISES=software-foundations
  - EXERCISES=concrete-semantics
# Don't build concrete-semantics, because Isabelle is so f****** slow
matrix:
  exclude:
    - env: EXERCISES=concrete-semantics
